"use client";

import { useEffect, useState } from "react";
import { BarChart3, Braces, Database, Files, GitBranch } from "lucide-react";
import { DashboardShell } from "@/components/dashboard/dashboard-shell";
import { PageHeading } from "@/components/dashboard/page-heading";
import { StatCard } from "@/components/dashboard/stat-card";
import {
  EmptyState,
  ErrorState,
  LoadingState,
} from "@/components/ui/status";
import { getInsights, InsightsResponse } from "@/services/insights";

export default function EmbeddingsPage() {
  const [data, setData] = useState<InsightsResponse | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getInsights().then(setData).catch((requestError: Error) => setError(requestError.message));
  }, []);

  const maxEmbeddings = Math.max(...(data?.repositories.map((repository) => repository.embeddingCount) || [0]), 1);

  return (
    <DashboardShell>
      <PageHeading eyebrow="Embedding Intelligence" title="Repository Embeddings" description="Inspect persisted embedding metadata generated by the ingestion pipeline. Counts and timestamps below are loaded from PostgreSQL through Prisma." />

      {!data && !error && (
        <LoadingState message="Loading embedding metadata..." />
      )}
      {error && <ErrorState message={error} />}

      {data && (
        <>
          <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <StatCard label="Total embeddings" value={data.summary.totalEmbeddings} detail="Persisted vector metadata records" icon={Database} accent="violet" />
            <StatCard label="Repositories" value={data.summary.totalRepositories} detail="Indexed repository workspaces" icon={GitBranch} accent="cyan" />
            <StatCard label="Processed files" value={data.summary.totalFiles} detail="Files observed during ingestion" icon={Files} accent="emerald" />
            <StatCard label="Average chunk size" value={`${data.summary.averageChunkLength} chars`} detail="Mean persisted chunk length" icon={Braces} accent="amber" />
          </div>

          {data.repositories.length === 0 ? (
            <EmptyState
              title="No embedding records yet"
              description="Ingest a repository from the dashboard to populate PostgreSQL metadata and the FAISS index."
            />
          ) : (
            <>
              <section className="mt-8 rounded-2xl border border-slate-800 bg-slate-900/55 p-6">
                <div className="flex items-center gap-3">
                  <BarChart3 className="h-5 w-5 text-cyan-300" />
                  <h2 className="text-lg font-semibold">Embeddings per repository</h2>
                </div>
                <div className="mt-7 space-y-5">
                  {data.repositories.map((repository) => (
                    <div key={repository.id}>
                      <div className="mb-2 flex justify-between gap-4 text-sm">
                        <span className="truncate text-slate-300">{repository.name}</span>
                        <span className="font-medium text-cyan-300">{repository.embeddingCount}</span>
                      </div>
                      <div className="h-2 overflow-hidden rounded-full bg-slate-800">
                        <div className="h-full rounded-full bg-gradient-to-r from-violet-500 to-cyan-400" style={{ width: `${Math.max((repository.embeddingCount / maxEmbeddings) * 100, 2)}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </section>

              <section className="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/55">
                <div className="border-b border-slate-800 p-6">
                  <h2 className="text-lg font-semibold">Repository embedding metadata</h2>
                  <p className="mt-2 text-sm text-slate-400">Ingestion timestamps and persisted vector counts by repository.</p>
                </div>
                <div className="overflow-x-auto">
                  <table className="w-full min-w-[720px] text-left text-sm">
                    <thead className="bg-slate-950/50 text-xs uppercase tracking-[0.16em] text-slate-500">
                      <tr><th className="px-6 py-4">Repository</th><th className="px-6 py-4">Embeddings</th><th className="px-6 py-4">Files</th><th className="px-6 py-4">Vector mapping</th><th className="px-6 py-4">Ingested</th></tr>
                    </thead>
                    <tbody className="divide-y divide-slate-800">
                      {data.repositories.map((repository) => (
                        <tr key={repository.id} className="text-slate-300">
                          <td className="px-6 py-4 font-medium text-white">{repository.name}</td>
                          <td className="px-6 py-4">{repository.embeddingCount}</td>
                          <td className="px-6 py-4">{repository.filesProcessed}</td>
                          <td className="max-w-48 truncate px-6 py-4 font-mono text-xs text-cyan-300">{repository.vectorRepositoryId}</td>
                          <td className="px-6 py-4 text-slate-400">{new Date(repository.ingestedAt).toLocaleString()}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </section>
            </>
          )}
        </>
      )}
    </DashboardShell>
  );
}
